const literals = {
  logOut: 'Log Out',
  logIn: 'Log In',
  email: 'Email',
  password: 'Password',
  text: 'Text',
  loading: 'Loading...',
  showPassword: 'Show Password',
  hidePassword: 'Hide Password',
  user: 'user',
  list: 'List',
  loadingAlt: 'Loading Morty',
  landingAlt: 'Landing Ricky Morty',
  welcome: 'Welcome to the Rick and Morty App',
  notFoundAlt: '404 Morty not found',
  notFoundSubtitle: 'Redirecting to homepage...',
  favorites: 'Favorite characters',
  normalList: 'All characters',
  back: 'Back',
  previous: 'Previous',
  next: 'Next',
  heartAlt: 'heartAlt',
  loginAlt: 'loginAlt',
};

export default literals;
